include themes/kanagawa.conf
include binds.conf

font_family JetBrainsMono Nerd Font Mono
font_size 14

cursor_shape beam
cursor_blink_interval 0.4

background_opacity 0.8
background_blur 25

window_padding_width 8
inactive_text_alpha 0.4
