gui:
  theme:
    activeBorderColor:
      - "#7e9cd8"
      - bold
    inactiveBorderColor:
      - "#727169"
    selectedLineBgColor:
      - "#2d4f67"
  showAllContainers: true
  returnImmediately: false
  wrapMainPanel: true
  scrollHeight: 2
  scrollPastBottom: true
  containerStatusHealthStyle: icon
logs:
  timestamps: false
  since: "60m"
  tail: "200"
commandTemplates:
  dockerCompose: docker compose
